export { default as UserIcon } from './UserIcon'
// export { default as TimesIcon } from './Times'
export { default as LockIcon } from './Lock'
export { default as EMailIcon } from './Email'
export { default as GithubIcon } from './Github'
export { default as GoogleIcon } from './Google'
// export { default as LogoutIcon } from './Logout'
// export { default as SettingIcon } from './Setting'
export { default as OpenEyeIcon } from './OpenEye'
export { default as CloseEyeIcon } from './CloseEye'
export { default as MagicLinkIcon } from './MagicLink'
// export { default as MenuOpenIcon } from './MenuOpen'
// export { default as MenuCloseIcon } from './MenuClose'
